### ISSUE TITLE
Java 8 Optional support

### ISSUE THREAD

**Issue by jhyot** [pholser/jopt-simple#101]
Hi!

Do you have any plans to support Java 8's `Optional` type for retrieving option arguments (as opposed to returning `null`s)?

Example in class `OptionSet`:

``` java
public <V> Optional<V> valueOfOptional( OptionSpec<V> option ) { ... }
```

(the method name could be improved)

Many aspects of `Optional` (e.g. the methods `ifPresent`, `orElse`, etc.) would make it quite nice to work with options.

**Comment by pholser** [comment]
@jhyot Thanks for your interest! I think this is a worthwhile addition.

**Comment by jhyot** [comment]
Although that would couple the library to Java 8+. I'm not sure if you want that yet, or if there is a way around that...?

**Comment by pholser** [comment]
@jhyot Would you mind looking at this pull request to see whether these additions meet your needs? Can you think of any other changes to make to support `Optional`?

If you're satisfied with these changes, I'll pursue adding tests, Javadoc, etc. Thanks!

**Comment by jhyot** [comment]
@pholser Looks good to me! I can't really comment on the new default method on the interface, because I haven't used those myself and don't really have an opinion on whether they are a good idea or not. I guess you are using it here to keep backwards compatibility...

**Comment by pholser** [comment]
This will appear in an upcoming 6.0 alpha.
