### ISSUE TITLE
EnumConverter should not be case-sensitive

### ISSUE THREAD

**Issue by martinpaljak** [pholser/jopt-simple#104]
Java enum-s are usually all caps, whereas command line is usually typed in small letters. Would be nice if EnumConverter could either ignore the case.

**Comment by pholser** [comment]
@martinpaljak Are you subclassing `EnumConverter` for your `enum` type and specifying `withValuesConvertedBy(...)`, or are you leaning on the default conversion for `enum` types (`valueOf()`)?

If the former, you can override `convert` to give the behavior you're looking for.

**Comment by martinpaljak** [comment]
I am. But I'll try to come up with a generic fix for the upstream, if that would be OK?

What makes me use the converter is the presence of the intended type in the help output.

**Comment by pholser** [comment]
@martinpaljak Sounds good. No harm in relaxing the `EnumConverter` to be case-insensitive.

**Comment by martinpaljak** [comment]
Any plans for a versioned release in near future?

**Comment by pholser** [comment]
@martinpaljak I'll cut a 5.0.x patch shortly.

**Comment by pholser** [comment]
@martinpaljak 5.0.3 should have your changes.
