### ISSUE TITLE
specifying a default together with a value converter

### ISSUE THREAD

**Issue by XSven** [pholser/jopt-simple#106]
Hi Paul,

in the project that I am currently working on I have defined the following ValueConverter

```
final class SwitchConverter implements ValueConverter<Boolean> {

    @Override
    public Boolean convert(final String value) {
        if ("on".equals(value)) {
            return Boolean.TRUE;
        } else if ("off".equals(value)) {
            return Boolean.FALSE;
        }
        throw new IllegalArgumentException(
                        String.format("String value '%s' must match '%s'.", value, valuePattern()));
    }

    @Override
    public Class<Boolean> valueType() {
        return Boolean.class;
    }

    @Override
    public String valuePattern() {
        return "/(?:on|off)/";
    }

}
```

The converter is used in the following specification

```
OptionParser parser = new OptionParser();
ArgumentAcceptingOptionSpec<Boolean> specification = parser.acceptsAll(Arrays.asList("t", "traceIncrements"), "Turns tracing of increment requests 'on' or 'off'.").withRequiredArg().describedAs("trace").withValuesConvertedBy(new SwitchConverter()).defaultsTo(Boolean.FALSE);
```

I have implemented a **HelpFormatter** that uses the **OptionDescriptor.defaultValues()** method. An extract of the help screen looks like this

...
-t trace
Turns tracing of increment requests 'on' or 'off'. It defaults to 'false'.
...

I want the user to use **on** and **off** as option argument values and I want to inform the user about the default. The default is displayed in the **SwitchConverter.convert()**ed way. That is wrong.

I don't understand why the default has to be specified as a Boolean (converted) value although value-conversion was specified/enabled. I would have expected that value conversion is also applied to the defaults.

A workaround might be possible if the **OptionDescriptor** interface would offer a method, e.g. **convertedBy()**, that returns the Class instance of the **ValueConverter** if specified. Saying that it seems that the **ValueConverter** interface needs a **reverse()** method that does the opposite of the **convert()** method.

Kind regards
Sven

**Comment by pholser** [comment]
@XSven This sounds reasonable. `OptionDescriptor.convertedBy()` and `ValueConverter.revert()`.

**Comment by halberd6** [comment]
@pholser is this issue resolved or still on-going?

**Comment by pholser** [comment]
@halberd6 As yet unresolved. Sorry for the delay -- day gig intrudes...8^)

**Comment by pholser** [comment]
@XSven @halberd6 Thinking about the proposed implementation...If I add a method to interface `ValueConverter`, this breaks all implementers of the interface. That is, until we abandon JDK < 8 (#108).

Would you be willing to wait until work is done to abandon JDK < 8, and then `ValueConverter.revert()` can have a default implementation so as not to break existing implementers?

**Comment by halberd6** [comment]
@pholser I did a workaround. For ArgumentAcceptingOptionSpec, the OptionDescriptor.argumentTypeIndicator() returns OptionDescriptor.convert.patternValue() if it is not null.

1. I add static method in SwitchConverter.class.
`static String revert(final Boolean value)`
2. While looping OptionDescriptor in our customized HelpFormatter, equals of SwitchConverter.valuePattern() and OptionDescriptor.argumentTypeIndicator() leads to  revert action.
`SwitchConverter.revert(OptionDescriptor.defaultValues().get(0))`

Although this looks unsafe / ugly, do you have any other suggestions?

**Comment by pholser** [comment]
@halberd6 @XSven At this point I can't think of a solution that I like better than introducing `ValueConverter.revert()`. Would you be OK with waiting until abandoning JDK < 8? I don't think it'll take too much effort before I can have a 6.0 alpha build available with this functionality.

**Comment by halberd6** [comment]
@pholser Yes, we can wait.

**Comment by pholser** [comment]
@halberd6 @XSven Please see the above pull request. Hopefully this will address your concerns!

**Comment by halberd6** [comment]
@pholser According to the changes in the pull request,  the problem we have could be solved. Looking forward to the next release.

**Comment by pholser** [comment]
@halberd6 @XSven This is in 6.0 alpha 1.
