### ISSUE TITLE
argument cant matched correctly

### ISSUE THREAD

**Issue by auroraxlh** [pholser/jopt-simple#115]
kafka used this package in source

once i typed a wrong command:
--------------------------------------------------------
kafka-topics.bat --create --zookeeper zdh165:2181/kafka --partitions 3 **--replication 3** --topic test11111
Error while executing topic command : replication factor: 3 larger than available brokers: 0
--------------------------------------------------------
In fact the right argument is "--replication-factor"

the jopt-simple parase "--replication "to "--replication-factor"

I note that in class AbbreviationMap function get cant matched chars strictly.
when command take sub-string argument , the check still success

I dont know  whether this is the future of jopt-simple or is a bug

**Comment by pholser** [comment]
@auroraxlh Would you mind to post your parser configuration? That way, I can reproduce your problem and hopefully offer a solution. Thanks!

**Comment by pholser** [comment]
@auroraxlh Are you asking whether `--replication` can/should be interpreted as having specified the configured option `replication-factor`? The answer is yes: by default, unambiguous prefixes of options are treated like the full option on the command line. So:

    OptionParser parser = new OptionParser();
    parser.accepts("verbose");

Any of `--v`, `--ve`, ... are accepted on the command line and treated as though you had typed `--verbose`.

To suppress this behavior, use the `OptionParser` constructor `OptionParser(boolean allowAbbreviations)` and pass a value of `false`.
