### ISSUE TITLE
Provide localization support for BuiltinHelpFormatter

### ISSUE THREAD

**Issue by domgold** [pholser/jopt-simple#72]
It would be nice to have localization support for the BuiltinHelpFormatter, like you did for the exception messages.

Currently the only way I found to localize BuiltinHelpFormatter is to provide my own implementation, copying all the code in my own class.

**Comment by pholser** [comment]
Agreed, a good idea.

**Comment by pholser** [comment]
See also #68.

**Comment by pholser** [comment]
@domgold Branch `feature/72/localization-of-help-formatter` has some work on this. Have a look and see whether this suits your needs -- if there's anything else you'd like to be localizable, or things that I've factored into bundles that don't need to be.

Also, translations are more than welcome for inclusion in the project.

Thanks!

**Comment by domgold** [comment]
That's exactly what we need! Do think you can release to central in the near future? 
I could provide French  and German translation at the end of our project, once the translation has been validated by the product owner.

**Comment by pholser** [comment]
@domgold Great, I'll merge this in. I anticipate cutting a 4.9 beta release this week.

**Comment by pholser** [comment]
@domgold oss.sonatype.org should have the latest 4.9 snapshot with these changes.

**Comment by pholser** [comment]
@domgold 4.9 beta 1 is at Maven central.

**Comment by domgold** [comment]
Thanks for notifying. I'll grive it a try next week.
