### ISSUE TITLE
OptionSet.specs() seems to be broken if OptionParser.nonOptions() is set

### ISSUE THREAD

**Issue by lbergelson** [pholser/jopt-simple#73]
If you create an option parser with .nonOptions() the resulting OptionSet seems to have broken behavior.
```
OptionParser parser = new OptionParser();
parser.nonOptions();
String[] args = {"one","two"};
OptionSet options = parser.parse(args);
```
calling  ``options.spec()``

returns ``[  [[Arguments]], [[Arguments]]]``

calling it again produces ``[[Arguments]]``

third and subsequent times its an empty list;

This seems to be because the remove call in the ``.spec()`` implementation only removes the first instance of arguments, not all of them.

**Comment by pholser** [comment]
Thanks for catching this!

**Comment by lbergelson** [comment]
Quick turnaround :+1:
