### ISSUE TITLE
Is it possible to do a release of the spec() bugfix? 

### ISSUE THREAD

**Issue by lbergelson** [pholser/jopt-simple#75]
Would it be possible to release the recent bug fix onto maven?

**Comment by pholser** [comment]
@lbergelson I'll deploy a snapshot to oss.sonatype.org shortly. If urgent, I'll make a 4.8.1. Let me know...

**Comment by pholser** [comment]
@lbergelson Latest 4.9 snapshot deployed to oss.sonatype.org. Let me know whether you are looking for a non-snapshot build.

**Comment by lbergelson** [comment]
@pholser Thanks!  That's great.
