### ISSUE TITLE
parser.nonOptions interaction with withOptionalArg in the case of boolean flags

### ISSUE THREAD

**Issue by lbergelson** [pholser/jopt-simple#76]
I would like to allow boolean flags to be specified in either of the following ways
`--someFlag` or `--someFlag true`  
This works well as long as there are no nonOptions

Say I have the following setup.
```
        OptionParser parser = new OptionParser();
        parser.accepts("flag").withOptionalArg().ofType(Boolean.class);
        parser.nonOptions() ;

        OptionSet parsed = parser.parse("--flag", "1","2");
```
I would like the following to pass:
```
        Assert.assertTrue(parsed.has("flag"));
        Assert.assertEquals(parsed.nonOptionArguments(), Arrays.asList("1","2"));
```
i.e.  `flag1` is seen, and the following two arguments are interpreted as `nonOptionArguments`.

What I actually end up with is `flag1` is `false`, and `nonOptionArguments` contains `3`

Is there a way I can achieve the desired behavior? 

Ideally:
`--flag true 1 2 3` is interpreted as `( --flag true ) ( 1 2 3 )` 
but 
`--flag 1 2 3`  is interpreted as `(--flag) (1 2 3)`
It seems possible for the specific case of booleans which could reasonably only accept variants of `true` or `false` but doesn't work if the type of `flag` is `String` 

Alternatively and possibly more coherently.  
`--flag=true 1 2 3` could be treated differently than `--flag true 1 2 3`

**Comment by pholser** [comment]
Thanks for your interest!

```java
public class Issue76Test {
    private OptionParser parser;
    private OptionSpec<Boolean> flag;
    private OptionSpec<Integer> nonOptions;

    @Before public void setUp() {
        parser = new OptionParser();
        flag = parser.accepts( "flag" ).withOptionalArg().ofType( Boolean.class );
        nonOptions = parser.nonOptions().ofType( Integer.class );
    }

    @Test public void suppliedExample() {
        OptionSet parsed = parser.parse( "--flag", "1", "2" );

        assertTrue( parsed.has( "flag" ) );
        assertFalse( flag.value( parsed ) );
        assertEquals( asList( 1, 2 ), nonOptions.values( parsed ) );
    }

    @Test public void abuttingValue() {
        OptionSet parsed = parser.parse( "--flag=true", "1", "2" );

        assertTrue( parsed.has( "flag" ) );
        assertTrue( flag.value( parsed ) );
        assertEquals( asList( 1, 2 ), nonOptions.values( parsed ) );
    }

    @Test public void nearValue() {
        OptionSpec<Boolean> flag = parser.accepts( "flag" ).withOptionalArg().ofType( Boolean.class );
        OptionSpec<Integer> nonOptions = parser.nonOptions().ofType( Integer.class );

        OptionSet parsed = parser.parse( "--flag", "true", "1", "2" );

        assertTrue( parsed.has( "flag" ) );
        assertTrue( flag.value( parsed ) );
        assertEquals( asList( 1, 2 ), nonOptions.values( parsed ) );
    }
}
```

In the latest stuff, `suppliedExample` doesn't work, but `abuttingValue` and `nearValue` do.

When an option is detected, and is known to accept an optional argument, and the following argument does not look like an option, it is consumed and treated as the argument to the option.

Conversion of option arguments to a specified type doesn't actually happen until you ask for the argument's value(s), not at parsing time. So, after parsing, the option set looks like:

    --flag: 1
    non-options: [2]

When we ask for the value of `flag`, we see that it's of type `boolean`, and attempt conversion using `Boolean.valueOf(String)`. The string `"1"` converts to `boolean` as `false`.

One possibility would be to say that if I've recognized an option that accepts an optional arg, and the next arg can't be converted to the appropriate type, then don't try to treat the arg as being attached to the option. 

In the meantime, your best bets are:

1) Make `flag` not accept an argument. The presence of the option indicates `true`, its absence `false`;
2) Require that `flag` accept an argument (`withRequiredArg`), with no optionality. Both `--flag=true` and `--flag true` will be treated equivalently.

**Comment by lbergelson** [comment]
Thanks for the response. You are a hero of rapid response times.

Both options 1 and 2 make total sense.  Unfortunately my project is absorbing two existing projects with legacy users.  Half of them want to specify flags like option 1 and half want option 2.  So I've been trying to accept either style. 
The third option I guess is to just require that they specify an end of options delimiter if using flag and nonOptions but it seems like really unexpected behavior.

I think the possibility you mention of checking that you can do the conversion before consuming the next argument is a good idea (it's kind of what I was expecting to happen).  The fact that anything converts to a `boolean` is a bit of a pain but could be special cased.  

The other option I see is to check the remaining arguments.  If none of them `looksLikeAnOption` then assume that they are all nonOptions.

**Comment by pholser** [comment]
@lbergelson Excellent - I think I will proceed as follows:

1) if I've recognized an option that accepts an optional arg, and the next arg can't be converted to the appropriate type, then don't try to treat the arg as being attached to the option.

2) Expose a `StrictJavaBooleanConverter` that accepts only `"true"` and `"false"`. You can then say:

    parser.accepts( "flag" )
        .withOptionalArg()
        .withValuesConvertedBy(new StrictJavaBooleanConverter());

How does this sound?

**Comment by lbergelson** [comment]
That sounds like it would exactly solve my problem.  I might relax `StrictJavaBooleanConverter` to be slightly more accepting.  I'd accept in case insensitive way `true/t/false/f`.   If you don't like that though I can always just write my own converter.

**Comment by pholser** [comment]
@lbergelson Latest 4.9 snapshot at oss.sonatype.org should have 1) above. I elected not to add a `StrictJavaBooleanConverter` -- hopefully rolling your own won't be too much trouble.

Thanks again! Interesting case!

**Comment by lbergelson** [comment]
Thank you!  Shouldn't be a problem to make my own.

**Comment by pholser** [comment]
@lbergelson Great - let me know how this goes. If all's well, can close the issue.

**Comment by lbergelson** [comment]
Sorry for the delay!  We had some distracting snow here.

It's working exactly as expected.  Thanks again.

Is a numbered release in maven central likely any time soon?  It's a bit scary building against a changing target.

**Comment by pholser** [comment]
Planning on cutting a 4.9 beta release this week.

**Comment by pholser** [comment]
@lbergelson 4.9 beta 1 is at Maven central.

**Comment by lbergelson** [comment]
Thanks.
