### ISSUE TITLE
mutuallyExclusive is missing from the 4.x tag

### ISSUE THREAD

**Issue by Yaneeve** [pholser/jopt-simple#78]
Sorry if this is not an issue, but I see that the mutuallyExclusive tag from commit d8d07a556d6d68de2fea22f3207c1ce6bef9ad55 has not been released with the 4.x tag. 
Is this purposeful?

**Comment by pholser** [comment]
@Yaneeve This is intentional -- it is intended for versions >= 5.

**Comment by Yaneeve** [comment]
Alright then, I'll close the issue. BTW, when is version 5 scheduled for?
