### ISSUE TITLE
OptionException message contains duplicate missing required options.

### ISSUE THREAD

**Issue by derekmahar** [pholser/jopt-simple#79]
Please remove the duplicate option names from the "Missing required option(s)" message that [`OptionException`](https://github.com/pholser/jopt-simple/blob/jopt-simple-4.9-beta-1/src/main/java/joptsimple/OptionException.java) produces when a required option has synonyms.
 
Example:

`OptionException` message contains three required options (one for each name):

````
Missing required option(s) [f/csv-file-name/ff, f/csv-file-name/ff, f/csv-file-name/ff].

Usage: java -jar fatca.jar com.opessoftware.fatca.App [options]

Option (* = required)                    Description                 
---------------------                    -----------                 
-?, -h, --help                           Display usage information.  
* -f, --csv-file-name, --ff <PATH_NAME>  Path name of input CSV file.
````

Expected behaviour is that `OptionException` message should contain only one required option that lists all names: 

```
Missing required option(s) [f/csv-file-name/ff].
```

**Comment by pholser** [comment]
Whoops! Sorry for this oversight. Will correct.

**Comment by pholser** [comment]
I've corrected this on both the 4.x and master branches.

**Comment by derekmahar** [comment]
Thank you!  Quick turnaround time!  (So do I get my name in the list of contributors? ;-))
