### ISSUE TITLE
When using an Enum class with ofType(), the argument parsing is case sensitive

### ISSUE THREAD

**Issue by jmMeessen** [pholser/jopt-simple#84]
I defined an option like this

````
        OptionSpec<QueueType> writeQueue = parser.accepts("writeQueue", "The configured queue to send messages to (INBOUND|OUTBOUND).")
                .withRequiredArg()
                .ofType(QueueType.class)
                .defaultsTo(QueueType.OUTBOUND);
````

My QueueType class is defined as
````
public enum QueueType {
    INBOUND("The inbound queue as configured in the Queue configuration file."),
    OUTBOUND("The outbound queue as configured in the Queue configuration file."),
    INVALID("Invalid Queue type");

    private String description;

    private QueueType(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
}
````

When I give the option's argument as lower case "inbound", the parsing fails with `joptsimple.OptionArgumentConversionException: Cannot parse argument 'inbound' of option writeQueue`

I tried to find a workaround for this but was not successful. Did I miss something ?

Jmm

**Comment by pholser** [comment]
@jmMeessen Thanks for your interest in JOpt Simple!

Without any other configuration, if you say that an option's value is to be of a particular type, then JOpt Simple will look for a constructor on that type with a single argument, of type `String`; or else a static `valueOf(String)` method to use to convert a value to the appropriate type. In the case of `enum`s, the `valueOf()` method is used. That method expects the raw value to exactly match the identifier used to declare one of the `enum`'s constants.

If you want to supply different conversion behavior, you can write your own `ValueConverter` and use `withValuesConvertedBy()` in your option spec configuration.

Hope this helps!

**Comment by jmMeessen** [comment]
Hello @pholser . Indeed, I like jOpt Simple very much and learning new tricks every day.

Thanks for the explanation and the hint. I'll dig in that direction. Could you point me an example of a custom ValueConverter ? Made only a 30 second search though.

**Comment by jmMeessen** [comment]
(Replying to myself)
I found a useful example here: `jopt-simple/src/main/java/joptsimple/util/DateConverter.java`

I will start from that.
