### ISSUE TITLE
BuiltinHelpFormatter width calculation is broken

### ISSUE THREAD

**Issue by kriegaex** [pholser/jopt-simple#85]
This refers to #16. I just noticed that ever since you implemented the column spacing option in version 4.4 (and even up to 4.9), it actually miscalculates the column width, wrapping words to way smaller width than necessary. The built-in formatter uses a default of 80 columns per line and a spacing of 2 in between parameter names and descriptions. For me it looks like this:

```
OpenbookCleaner usage: java ... [options] <book_id>*

Option                     Description                           
------                     -----------                           
-?, --help                 Display this help text                
-c, --check-avail          Check Galileo homepage for available  
                             books, compare with known ones      
-d, --download-dir <File>  Download directory for openbooks; must
                             exist (default: .)                  
-l, --log-level <Integer>  Log level (0=normal, 1=verbose,       
                             2=debug, 3=trace) (default: 0)      
-m, --check-md5            Download all known books without      
                             storing them, verifying their MD5   
                             checksums (slow! >1 Gb download)    
-t, --threading <Integer>  Threading mode (0=single, 1=multi);   
                             single is slower, but better for    
                             diagnostics) (default: 1)           
-w, --write-config         Write editable book list to config.   
                             xml, enabling you to update MD5     
                             checksums or add new books          
```

I.e. the overall width is only 65. I expect it to use as much horizontal space as expected, i.e. 80 colums. This would look like this:

```
OpenbookCleaner usage: java ... [options] <book_id>*

Option                     Description
------                     -----------
-?, --help                 Display this help text
-c, --check-avail          Check Galileo homepage for available books, compare
                             with known ones
-d, --download-dir <File>  Download directory for openbooks; must exist
                             (default: .)
-l, --log-level <Integer>  Log level (0=normal, 1=verbose, 2=debug, 3=trace)
                             (default: 0)
-m, --check-md5            Download all known books without storing them,
                             verifying their MD5 checksums (slow! >1 Gb
                             download)
-t, --threading <Integer>  Threading mode (0=single, 1=multi); single is
                             slower, but better for diagnostics) (default: 1)
-w, --write-config         Write editable book list to config.xml, enabling
                             you to update MD5 checksums or add new books
```

There is another ugly, little bug: `config.xml` is falsely word-wrapped after the dot, even though there is no space after the dot, which would indicate a new word.

I also wonder why you fill the output with trailing whitespace, which is unnecessary, but rather of cosmetic nature.

**Comment by pholser** [comment]
@kriegaex Absolutely right; the intent was for the description column to consume as much horizontal space as it can. Clearly it does not. I will look at this, and at the line-breaking behavior.

Trimming each output line shouldn't be a problem either.

**Comment by kriegaex** [comment]
Thanks for the swift reaction. :-)

Until you roll a new release, my (rather odd) workaround to get 80 columns and 4 spaces is to call

    formatHelpWith(new BuiltinHelpFormatter(106, 4));

**Comment by pholser** [comment]
@kriegaex I've pushed a 4.10 snapshot to oss.sonatype.org -- see whether or not this suits your needs. This is also merged to master.

I am relying on the behavior of `BreakIterator.getLineInstance()` to break long lines for me -- I'm not sure how well it copes with abbreviations like "e.g." and dotted file names. Also unsure how much effort it'd be to coax a `BreakIterator` into doing better, or replacing it with something else.

**Comment by pholser** [comment]
@kriegaex Considering the matter closed.
