### ISSUE TITLE
Should MissingRequiredOptionsException be public

### ISSUE THREAD

**Issue by fzakaria** [pholser/jopt-simple#87]
I can't seem to catch MissingRequiredOptionsException as its package local scope.

Wouldn't I want to catch this and just print the friendly help message ?

**Comment by pholser** [comment]
Would catching `OptionException` get you the behavior you're looking for?

**Comment by fzakaria** [comment]
Yea thats what I did.
Just feels weird accessor.

I wanted to catch specifically MissingRequiredOptions and print help message.

Close if you want.

**Comment by pholser** [comment]
My intent was that catching `OptionException` and printing the result of its `getMessage()` would be sufficient for most needs. In my opinion, publishing lots of specific exception types clutters the API, and once it's published, it must be supported longer-term. I hope that catching `OptionException` and showing its message, or better yet, letting the exception propagate to let the JVM show the message and stack trace on the console, will be enough.
