### ISSUE TITLE
Ability to disable matching abbreviated options

### ISSUE THREAD

**Issue by lbergelson** [pholser/jopt-simple#88]
I'd like to be able to disable matching abbreviated long options.

The reasoning is as follows.  We have a toolkit that has several distinct CLI tools.  These share many options between them, but not every option.  We've had user confusion, because all tools accept --verbosity, and usually people specify this as -v.  However, some tools specify an argument called --variants, and users get confused why suddenly -v does something different.

I'm happy to submit a pull request to add this functionality, but I wanted to get your input on the preferred way to proceed.  

1.  Add an additional `OptionParser` constructor that takes a boolean to accept abbreviated options or not.  Extract an interface from `AbbreviationMap` and add an new `NonAbbreviatingMap`.  Choose the appropriate one at construction time.

  This doesn't really match the style of the existing code so well, and introduces and extra class and interface.  However, it will not complicate the logic in OptionParser at all.

2.  Add a setter to toggle abbreviated options on or off.  Add a second map that stores all the input keys and add logic to select from the abbreviated map or not abbreviated map when necessary.  

  This would avoid adding any new classes, but it would add a bunch of ugly if statements.  It matches the existing style of using a no-args constructor and setting options to the parser on the fly though.

3.  Some other design I haven't proposed.

Hopefully you feel like this is a reasonable feature.

**Comment by pholser** [comment]
@lbergelson Off hand, I don't have a preference regarding implementation. Interested to see your PR!
