### ISSUE TITLE
Public API leaks non-public classes

### ISSUE THREAD

**Issue by pniederw** [pholser/jopt-simple#95]
The public `OptionSpecBuilder` class has package-private `NoArgumentOptionSpec` and `AbstractOptionSpec` superclasses. Whereas Java doesn't prevent such visibility leakages, other languages do. Specifically, I haven't found a way to call methods such as `AbstractOptionSpec#forHelp` from Kotlin. Can this be fixed?

**Comment by pholser** [comment]
@pniederw I'll look into this...thanks

**Comment by pholser** [comment]
@pniederw Looks like the resolution for #93 addressed this. I think I will cut a 5.0.2 release with this in it soon.

**Comment by pholser** [comment]
@pniederw 5.0.2 is available -- does it solve your problem? Thanks!

**Comment by pholser** [comment]
Haven't heard back on this. Considering the issue resolved, unless I hear otherwise. Thanks!
