### ISSUE TITLE
Showing "String" as a type indicator for options that require String arguments 

### ISSUE THREAD

**Issue by XSven** [pholser/jopt-simple#96]
It seems that printHelpOn() does not print the type of a required option argument in angle brackets, if the type is a "String". I feel the printed help is misleading because it looks like such an option has no argument at all. I worked around this misusing the describedAs() method. Example:

```
parser.accepts("p", "set prefix information").withRequiredArg().ofType(String.class);
parser.accepts("s", "set suffix information").withRequiredArg().describedAs("String").ofType(String.class);
         
Option        Description                         
------        -----------
-p            set prefix information              
-s <String>   set suffix information              

```

**Comment by XSven** [comment]
Hi Paul,

very much appreciated your feedback

> I believe not showing "String" as a type indicator for options that require String arguments is an oversight on my part.

Kind regards
Sven

**Comment by pholser** [comment]
@XSven Check out the PR referenced above -- let me know how this looks. Thanks!

**Comment by XSven** [comment]
Hi Paul that is perfect now. Who is going to close the issue now you or myself? Sorry this is the first time I attending to such a collaboration. Kind regards Sven

**Comment by pholser** [comment]
After I merge the PR, feel free to close the issue.
